### ISSUE TITLE
Error: Ejecutando migasfree -u sobre docker

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#82]
Con la versión 4.15 se produce el siguiente error:

```
Traceback (most recent call last):
  File "/usr/bin/migasfree", line 17, in <module>
    migasfree_client.client.main()
  File "/usr/lib/python2.7/site-packages/migasfree_client/client.py", line 903, in main
    mfc = MigasFreeClient()
  File "/usr/lib/python2.7/site-packages/migasfree_client/client.py", line 66, in __init__
    self._user_is_not_root()
  File "/usr/lib/python2.7/site-packages/migasfree_client/command.py", line 209, in _user_is_not_root
    if not self._check_user_is_root():
  File "/usr/lib/python2.7/site-packages/migasfree_client/command.py", line 206, in _check_user_is_root
    return utils.get_user_info(os.environ.get('USER'))['gid'] == 0
  File "/usr/lib/python2.7/site-packages/migasfree_client/utils.py", line 320, in get_user_info
    _info = pwd.getpwnam(user)
TypeError: must be string, not None
```

**Comment by agacias** [comment]
Con la versión "master" se produce el error:
```
Traceback (most recent call last):
  File "/usr/bin/migasfree", line 17, in <module>
    migasfree_client.client.main()
  File "/usr/lib/python2.7/site-packages/migasfree_client/client.py", line 903, in main
    mfc = MigasFreeClient()
  File "/usr/lib/python2.7/site-packages/migasfree_client/client.py", line 66, in __init__
    self._user_is_not_root()
  File "/usr/lib/python2.7/site-packages/migasfree_client/command.py", line 209, in _user_is_not_root
    if not self._check_user_is_root():
  File "/usr/lib/python2.7/site-packages/migasfree_client/command.py", line 206, in _check_user_is_root
    return utils.get_user_info(os.environ.get('USER'))['gid'] == 0
  File "/usr/lib/python2.7/site-packages/migasfree_client/utils.py", line 291, in get_user_info
    _info = pwd.getpwnam(user)
TypeError: must be string, not None 
```

**Comment by jact** [comment]
Dentro del contenedor docker no existe la variable de entorno USER. Estableciéndola en el Dockerfile, el cliente funciona sin errores:

`ENV USER "root"`
