### ISSUE TITLE
Bug: Capturando hw en debian:buster

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#94]
En debian:buster en el cliente se produce el siguiente error al capturar el HW y sale del programa sin terminar la sincronización.

```
******************** Capturing hardware information... *********************
*********************************** Ok
Traceback (most recent call last):
  File "/usr/bin/migasfree", line 17, in <module>
    migasfree_client.client.main()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/client.py", line 968, in main
    mfc.run()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/client.py", line 945, in run
    self._update_system()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/client.py", line 620, in _update_system
    self._update_hardware_inventory()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/client.py", line 503, in _update_hardware_inventory
    _hardware = json.loads(_output)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 11 column 8 (char 225)

```

**Comment by agacias** [comment]
Además de corregir el bug se debería controlar que si falla la captura de HW por cualquier motivo se mande un error al servidor y/o se envie un HW vacío y continue con la sincronización.
